{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "21775a1c",
   "metadata": {},
   "source": [
    "# Módulo 7: Manejo de excepciones\n",
    "\n",
    "## Parte 3: Manejo de excepciones usando bloques try-except\n",
    "\n",
    "En Python, puede manejar excepciones usando el bloque try-except. Esta construcción le permite capturar y manejar excepciones específicas\n",
    "que pueden ocurrir durante la ejecución de su código. Al manejar las excepciones, puede evitar que su programa se bloquee y proporcionar\n",
    "acciones alternativas o mensajes de error a los usuarios.\n",
    "\n",
    "### 3.1. Sintaxis del bloque try-except\n",
    "\n",
    "El bloque try-except consiste en el bloque try, donde se coloca el código que podría generar una excepción, y uno o más bloques except que definen cómo manejar excepciones específicas.\n",
    "\n",
    "Aquí está la sintaxis básica:\n",
    "\n",
    "```python\n",
    "try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except tipo de excepción:\n",
    "     # Código de manejo de excepciones\n",
    "     #...\n",
    "```\n",
    "\n",
    "En el bloque except, especifica el tipo de excepción que desea manejar mencionando ExceptionType. Si una excepción ocurre en el bloque try, se ejecuta el bloque except correspondiente.\n",
    "\n",
    "Por ejemplo, si desea manejar un ValueError, puede escribir el siguiente código:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4f9ee41",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     edad = int(input(\"Ingrese su edad: \"))\n",
    "except ValueError:\n",
    "     print(\"Edad no válida. Ingrese un número entero válido.\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "d9a32061",
   "metadata": {},
   "source": [
    "En el ejemplo anterior, si el usuario ingresa un valor no entero para la edad, se generará un ValueError y el correspondiente except\n",
    "se ejecutará el bloque ValueError, mostrando el mensaje de error.\n",
    "\n",
    "### 3.2. Manejo de múltiples excepciones\n",
    "\n",
    "Puede manejar varias excepciones mediante el uso de varios bloques de excepción. Cada bloque except puede manejar un tipo específico de excepción.\n",
    "Se ejecutará el primer bloque de excepción que coincida con el tipo de excepción generado y se omitirán los bloques de excepción subsiguientes.\n",
    "\n",
    "```python\n",
    "  try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except ValueError:\n",
    "     # Código de manejo de excepciones para ValueError\n",
    "     #...\n",
    "except TypeError:\n",
    "     # Código de manejo de excepciones para TypeError\n",
    "     #...\n",
    "```\n",
    "\n",
    "En el ejemplo anterior, si ocurre un ValueError, se ejecutará el primer bloque except ValueError. Si ocurre un TypeError, el segundo\n",
    "excepto que se ejecutará el bloque TypeError.\n",
    "\n",
    "Por ejemplo, si desea manejar varias excepciones, puede escribir el siguiente código:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3bcba3ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     edad = int(input(\"Ingrese su edad: \"))\n",
    "     resultado = 10 / edad\n",
    "except ValueError:\n",
    "     print(\"Edad no válida. Ingrese un número entero válido.\")\n",
    "except ZeroDivisionError:\n",
    "     print(\"Error: No se puede dividir por cero\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "ca17f1f2",
   "metadata": {},
   "source": [
    "En este ejemplo, agregamos otro bloque excepto para manejar la excepción ZeroDivisionError. Si el usuario ingresa una edad de 0, ocurrirá un ZeroDivisionError al intentar calcular 10/edad. El segundo bloque de excepción captará esta excepción específica y mostrará un mensaje de error apropiado.\n",
    "\n",
    "### 3.3. Manejo de múltiples excepciones con un solo bloque de excepción\n",
    "\n",
    "Si desea manejar varias excepciones con el mismo código de manejo, puede especificar varios tipos de excepciones dentro de un solo bloque excepct.\n",
    "Esto es útil cuando desea proporcionar la misma lógica de manejo de errores para diferentes tipos de excepciones.\n",
    "\n",
    "```python\n",
    "try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except (ExceptionType1, ExceptionType2):\n",
    "     # Código de manejo de excepciones para ExceptionType1 y ExceptionType2\n",
    "     #...\n",
    "```\n",
    "\n",
    "Usando el mismo ejemplo, si desea manejar excepciones en el mismo bloque except, puede escribir el siguiente código:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d84e730",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     edad = int(input(\"Ingrese su edad: \"))\n",
    "     resultado = 10 / edad\n",
    "except (ValueError, ZeroDivisionError):\n",
    "     print(\"Edad inválida o división por cero\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "bfbbc7a1",
   "metadata": {},
   "source": [
    "En este ejemplo, usamos un solo bloque de excepción seguido de paréntesis para definir una tupla de tipos de excepción (ValueError, ZeroDivisionError). Esto nos permite manejar las excepciones ValueError y ZeroDivisionError en el mismo bloque. Si ocurre alguna de estas excepciones, se ejecutará el código dentro del bloque de excepción y se mostrará el mensaje de error correspondiente.\n",
    "\n",
    "### 3.4. Manejo de todas las excepciones\n",
    "\n",
    "Para manejar todas las demás excepciones que no son capturadas explícitamente por bloques de excepción específicos, puede usar un bloque de excepción genérico\n",
    "sin especificar el tipo de excepción. Sin embargo, generalmente se recomienda detectar excepciones específicas siempre que sea posible para proporcionar un manejo de errores más significativo.\n",
    "\n",
    "Aquí hay un ejemplo de un bloque except genérico:\n",
    "\n",
    "```python\n",
    "try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except:\n",
    "     # Código genérico de manejo de excepciones\n",
    "     #...\n",
    "```\n",
    "\n",
    "En el ejemplo anterior, si ocurre alguna excepción que no es detectada por los bloques except anteriores, se ejecutará el bloque except genérico."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b07325b",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     edad = int(input(\"Ingrese su edad: \"))\n",
    "     resultado = 10 / edad\n",
    "except Exception as e:\n",
    "     print(\"Ha ocurrido un error:\", str(e))"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "74fffe31",
   "metadata": {},
   "source": [
    "En este ejemplo, usamos un solo bloque de except sin especificar ningún tipo de excepción en particular. Esto nos permite manejar todas las excepciones que pueden ocurrir dentro del bloque try.\n",
    "\n",
    "La clase Exception sirve como clase base para todas las excepciones integradas en Python.\n",
    "\n",
    "### 3.5. Manejo de excepciones específicas de manera jerárquica\n",
    "\n",
    "Al manejar excepciones específicas, es importante tener en cuenta la jerarquía de excepciones. Python tiene una jerarquía integrada de excepciones,\n",
    "  donde algunas excepciones son subclases de otras. Puede manejar las excepciones de manera jerárquica comenzando con las más específicas y avanzando hacia otras más generales.\n",
    "\n",
    "Por ejemplo, si desea manejar una excepción específica como FileNotFoundError o su excepción mas general IOError, puede escribir\n",
    "el código de la siguiente manera:\n",
    "\n",
    "```python\n",
    "try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except FileNotFoundError:\n",
    "     # Código de manejo de excepciones para FileNotFoundError\n",
    "     #...\n",
    "except IOError:\n",
    "     # Código de manejo de excepciones para IOError\n",
    "     #...\n",
    "```\n",
    "\n",
    "En el ejemplo anterior, si se produce un FileNotFoundError, se ejecutará el primer bloque excepto FileNotFoundError. Si un IOError\n",
    "ocurre que no es un FileNotFoundError, se ejecutará el segundo bloque excepto IOError.\n",
    "\n",
    "Aquí hay un ejemplo que demuestra el manejo jerárquico de excepciones:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9af336b",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     # Código que puede generar excepciones\n",
    "     x = int(input(\"Ingrese un número: \"))\n",
    "     y = int(input(\"Ingrese otro número: \"))\n",
    "     resultado = x / y\n",
    "except ValueError:\n",
    "     # Manejar tipos de excepción específicos primero\n",
    "     print(\"Entrada no válida. Ingrese números enteros válidos.\")\n",
    "except ZeroDivisionError:\n",
    "     # Manejar tipos de excepción más específicos a continuación\n",
    "     print(\"Error: No se puede dividir por cero\")\n",
    "except Exception:\n",
    "     # Manejar tipos de excepción más generales al final\n",
    "     print(\"Ha ocurrido un error\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "88f5847b",
   "metadata": {},
   "source": [
    "Primero, manejamos la excepción ValueError, que ocurre cuando el usuario ingresa un valor no entero. Proporcionamos un mensaje de error apropiado para este tipo de excepción específico. A continuación, manejamos la excepción ZeroDivisionError, que ocurre cuando el usuario ingresa 0 como segundo número para la división. Nuevamente, mostramos un mensaje de error específico para este tipo de excepción. Por último, tenemos un bloque de excepciones más general para manejar las excepciones restantes que no fueron detectadas por los bloques de excepciones específicos. Esto actúa como un bloque general para manejar excepciones inesperadas o desconocidas.\n",
    "\n",
    "Al organizar el manejo de excepciones de manera jerárquica, podemos abordar tipos de excepción específicos primero y gradualmente manejar tipos de excepción más generales si es necesario. Este enfoque permite un manejo de excepciones más específico y preciso en función de los escenarios de error específicos.\n",
    "\n",
    "### 3.6. El bloque else\n",
    "\n",
    "Además de los bloques try y except, puede incluir un bloque else opcional después de todos los bloques except. El código dentro del bloque else se ejecuta si no se producen excepciones en el bloque try. A menudo se utiliza para realizar acciones de limpieza o adicionales que\n",
    "solo debería ocurrir cuando no se generan excepciones.\n",
    "\n",
    "```python\n",
    "try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except tipo de excepción:\n",
    "     # Código de manejo de excepciones\n",
    "     #...\n",
    "else:\n",
    "     # Código que se ejecuta si no ocurren excepciones\n",
    "     #...\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68243464",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     # Código que puede generar excepciones\n",
    "     x = int(input(\"Ingrese un número: \"))\n",
    "     y = int(input(\"Ingrese otro número: \"))\n",
    "     resultado = x / y\n",
    "except ValueError:\n",
    "     # Manejar tipos de excepción específicos primero\n",
    "     print(\"Entrada no válida. Ingrese números enteros válidos.\")\n",
    "except ZeroDivisionError:\n",
    "     # Manejar tipos de excepción más específicos a continuación\n",
    "     print(\"Error: No se puede dividir por cero\")\n",
    "except Exception:\n",
    "     # Manejar tipos de excepción más generales al final\n",
    "     print(\"Ha ocurrido un error\")\n",
    "else:\n",
    "     # Código a ejecutar si no ocurre ninguna excepción\n",
    "     print(\"Resultado de la división:\", resultado)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "c7944f0c",
   "metadata": {},
   "source": [
    "En este código actualizado, agregamos un bloque else después de los bloques excepto. El código dentro del bloque else solo se ejecutará si no ocurre ninguna excepción en el bloque try. En este caso, simplemente muestra el resultado de la división.\n",
    "\n",
    "El bloque else proporciona una forma de separar el código que debe ejecutarse cuando no se produce ninguna excepción, lo que hace que el código sea más legible y claro. Es especialmente útil cuando queremos realizar determinadas acciones solo si el código del bloque try se ejecuta correctamente.\n",
    "\n",
    "Tenga en cuenta que el bloque else es opcional y se puede omitir si no se debe realizar ninguna acción específica cuando no se produce una excepción.\n",
    "\n",
    "### 3.7. El bloque finally\n",
    "\n",
    "Otro bloque opcional que se puede usar con el bloque de prueba except es el bloque finally. El código dentro del bloque finally siempre se ejecuta, independientemente de si se generó una excepción o no. Se utiliza comúnmente para liberar recursos, cerrar archivos, o realizar otras acciones de limpieza.\n",
    "\n",
    "```python\n",
    "try:\n",
    "     # Código que podría generar una excepción\n",
    "     #...\n",
    "except tipo de excepción:\n",
    "     # Código de manejo de excepciones\n",
    "     #...\n",
    "finally:\n",
    "     # Código que siempre se ejecuta\n",
    "     #...\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ed8ebc9b",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "     # Código que puede generar excepciones\n",
    "     x = int(input(\"Ingrese un número: \"))\n",
    "     y = int(input(\"Ingrese otro número: \"))\n",
    "     resultado = x / y\n",
    "except ValueError:\n",
    "     # Manejar tipos de excepción específicos primero\n",
    "     print(\"Entrada no válida. Ingrese números enteros válidos.\")\n",
    "except ZeroDivisionError:\n",
    "     # Manejar tipos de excepción más específicos a continuación\n",
    "     print(\"Error: No se puede dividir por cero\")\n",
    "except Exception:\n",
    "     # Manejar tipos de excepción más generales al final\n",
    "     print(\"Ha ocurrido un error\")\n",
    "else:\n",
    "     # Código a ejecutar si no ocurre ninguna excepción\n",
    "     print(\"Resultado de la división:\", resultado)\n",
    "finally:\n",
    "     # Código que siempre se ejecutará, independientemente de las excepciones\n",
    "     print(\"Finalmente bloque ejecutado\")"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "id": "10e4f2de",
   "metadata": {},
   "source": [
    "En este código actualizado, agregamos un bloque finally después de los bloques except y else. El código dentro del bloque finally siempre se ejecutará, sin importar si ocurrió una excepción o no.\n",
    "\n",
    "El bloque finally es útil para limpiar recursos o realizar acciones que deberían ocurrir independientemente del resultado del código en el bloque de prueba. Garantiza que se ejecute cierto código, incluso si se genera y detecta una excepción.\n",
    "\n",
    "En este ejemplo, el bloque finally imprime un mensaje que indica que se ha ejecutado.\n",
    "\n",
    "Tenga en cuenta que el bloque finally es opcional y se puede omitir si no es necesario realizar una limpieza o acción específica, independientemente de las excepciones.\n",
    "\n",
    "### 3.8. Resumen\n",
    "\n",
    "El manejo de excepciones usando el bloque try-except es una técnica poderosa en Python para lidiar con errores potenciales y asegurar el\n",
    "ejecución fluida de su código. Al detectar y manejar excepciones, puede proporcionar mejores mensajes de error, recuperarse de situaciones inesperadas y evitar que su programa se bloquee.\n",
    "\n",
    "La captura de excepciones específicas le permite manejar diferentes tipos de excepciones de manera diferente en su código. especificando\n",
    "el tipo de excepción en el bloque excepto, puede proporcionar un manejo de errores personalizado para escenarios específicos. Puedes atrapar una sola\n",
    "excepción específica, manejar múltiples excepciones específicas o manejar múltiples excepciones con un solo bloque de excepción.\n",
    "Es importante manejar las excepciones de manera jerárquica para garantizar que se manejan adecuadamente."
   ]
  }
 ],
 "metadata": {
  "jupytext": {
   "cell_metadata_filter": "-all",
   "main_language": "python",
   "notebook_metadata_filter": "-all"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
